---
stages:
  - lint
  - deploy

# CI Lint tool
# https://gitlab.com/toshi_click/server/ansible_for_server/-/ci/lint

# サブモジュールを更新する場合にはこれを有効にする
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  # to avoid this problem:
  # UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 140: ordinal not in range(128)
  LANG: ja_JP.UTF-8

.deploy_default: &deploy_default
  #  stage: deploy
  image: toshiclick/ci-ansible
  before_script:
    - ansible-galaxy install -r requirements.yml -p roles --force
#    - echo -e "$VAULT_PASS" > ~/.ssh/.ansible_vault_pass
#    - chmod 644 ~/.ssh/.ansible_vault_pass
#  after_script:
#    - rm -f ~/.ssh/.ansible_vault_pass

cache:
  # ジョブ毎にキャッシュを共有する設定
  key: "$CI_JOB_NAME"
  untracked: true

ansiblelint:
  stage: lint
  image: toshiclick/ci-ansible
  script:
    - pip install ansible-lint
    - ansible-lint all.yml -c .ansible-lint
  except:
    - schedules

ansible_syntax:
  stage: lint
  <<: *deploy_default
  script:
#    - ansible-playbook -i hosts/all.yml all.yml --syntax-check --vault-pass ~/.ssh/.ansible_vault_pass
    - ansible-playbook -i hosts/all.yml all.yml --syntax-check
  only:
    # 実行されるブランチを指定(vault passはプロテクトブランチでしか取れないようにしているので。)
    refs:
      - master
  except:
    - schedules
