---
ansible_ssh_pass: "{{ crypt_ansible_ssh_pass }}"
ansible_become_pass: "{{ crypt_ansible_become_pass }}"

vlans:
  - name: "Vlan1"
    id: 1
    state: active
    shutdown: disabled
    mtu: 1500
  - name: "Vlan99"
    id: 99
    state: active
    shutdown: disabled
    mtu: 1500
  - name: "Vlan77"
    id: 77
    state: active
    shutdown: disabled
    mtu: 1500
  - name: "Vlan100"
    id: 100
    state: active
    shutdown: disabled
    mtu: 1500
  - name: "Vlan177"
    id: 177
    state: active
    shutdown: disabled
    mtu: 1500
