---
ansible_ssh_pass: "{{ crypt_ansible_ssh_pass }}"
ansible_become_pass: "{{ crypt_ansible_become_pass }}"

vlans:
  - name: "Vlan1"
    id: 1
    state: active
    shutdown: disabled
    mtu: 1500
  - name: "Vlan99"
    id: 99
    state: active
    shutdown: disabled
    mtu: 1500
  - name: "Vlan77"
    id: 77
    state: active
    shutdown: disabled
    mtu: 1500
  - name: "Vlan100"
    id: 100
    state: active
    shutdown: disabled
    mtu: 1500
  - name: "Vlan177"
    id: 177
    state: active
    shutdown: disabled
    mtu: 1500

dhcps:
  - name: "toshipc01"
    host: 172.28.77.10
    subnet: 255.255.255.0
    address: 00d8.61a1.519b
    identifier: 0100.d861.a151.9b
  - name: "lenovo-p14s"
    host: 172.28.77.21
    subnet: 255.255.255.0
    address: b0a4.60c2.ce05
    identifier: 01b0.a460.c2ce.05
  - name: "shigure.test"
    host: 172.28.177.100
    subnet: 255.255.255.0
    address: 7085.c240.d20b
    identifier: 0170.85c2.40d2.0b
  - name: "mayu.test"
    host: 172.28.177.200
    subnet: 255.255.255.0
    address: 0025.22a0.b04c
    identifier: 0100.2522.a0b0.4c
  - name: "ranko.test"
    host: 172.28.100.64
    subnet: 255.255.255.0
    address: 6805.CA2B.B2F4
    identifier: 0168.05CA.2BB2.F4
  - name: "dns.test"
    host: 172.28.100.53
    subnet: 255.255.255.0
    address: 5254.006f.cf73
    identifier: 0152.5400.6fcf.73
#  - name: "monitoring.test"
#    host: 172.28.100.111
#    subnet: 255.255.255.0
#    address:
#  - name: "k8s-api.test"
#    host: 172.28.100.131
#    subnet: 255.255.255.0
#    address:
#  - name: "k8s-master1.test"
#    host: 172.28.100.132
#    subnet: 255.255.255.0
#    address:
#  - name: "k8s-master2.test"
#    host: 172.28.100.133
#    subnet: 255.255.255.0
#    address:
#  - name: "k8s-master3.test"
#    host: 172.28.100.134
#    subnet: 255.255.255.0
#    address:
#  - name: "k8s-worker1.test"
#    host: 172.28.100.135
#    subnet: 255.255.255.0
#    address:
#  - name: "k8s-worker2.test"
#    host: 172.28.100.136
#    subnet: 255.255.255.0
#    address:
